### ISSUE TITLE
Clean up the ASR-Chaos

### ISSUE THREAD

**Issue by ogruetzmann** [ogruetzmann/EDMM-Starterpaket#2]
Unnötige ASRs entfernen, auf eine Version festlegen (GRP und Topsky?)

**Comment by jannikvogel** [comment]
Vorschlag: An EDFF angelehnt Trainee-ASRs und PRO-ASRs zur Verfügung stellen? PRO für eine möglichst reale Nachbildung des Scopes, Trainee für die Ausbildung (Wegpunkt-Namen, allgemein mehr Informationen)

**Comment by ogruetzmann** [comment]
@jannikvogel würde ich nicht machen, ich denke, ich würde eher Traineemaps in Topsky einbinden über eine TopSkyLocal.txt. Lieber einheitliche ASRs.
Die Trainees sollen sich ruhig direkt dran gewöhnen, wie das aussieht.

**Comment by jannikvogel** [comment]
@Lotus3xiG3 sind die CTR_APP und CTR_FULL.asr von dir? Wenn ja, was können die tolles? :D

**Comment by Lotus3xiG3** [comment]
Yes, das sind meine. Das ist meine Interpretation von aufgeräumten und dennoch informativen ASRs. Diese enthalten auch die entsprechenden TopSky-Settings.
