### ISSUE TITLE
Welche Plugins werden gebraucht?

### ISSUE THREAD

**Issue by jannikvogel** [ogruetzmann/EDMM-Starterpaket#3]
Klar: GRP und Topsky, AfV-Bridge und ESCLines
Raus: vSMR
@ogruetzmann: Wofür braucht man noch Display Elements und ESTagItems? Braucht man noch das Mode S PlugIn, wenn man Sqs über Topsky assigned?

**Comment by jannikvogel** [comment]
RDF-Plugin sollte auch raus, weil in Topsky bereits vorhanden

**Comment by ogruetzmann** [comment]
Display Elements hab ich selbst nie genutzt -> keine Ahnung.
ESTagItems kann in jedem Fall raus. Das war damals meine Lösung für die Vertical Speed, aber das macht ja Topsky selbst.

Mode S würd ich noch drin lassen, falls nicht jeder das Topsky Assignment nutzt.

**Comment by jannikvogel** [comment]
closed with merge of jannik-working
